# Generated by Django 5.1.6 on 2025-03-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0004_category_product_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('administrator', 'Administrator')], default='farmer', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExpertProfile',
        ),
        migrations.DeleteModel(
            name='MerchantProfile',
        ),
    ]
